### ISSUE TITLE
import: freifunk defaults and profiles: add sections for 802.11s

### ISSUE THREAD

**Issue by SvenRoederer** [freifunk/openwrt-packages#1]
this will follow up https://github.com/openwrt/luci/issues/2503 after moving from OpenWrt-LuCI repo

**Comment by SvenRoederer** [comment]
this will follow up openwrt/luci#642 after moving from OpenWrt-LuCI repo

**Comment by pmelange** [comment]
There is general consensus in the freifunk-berlin group to move to 802.11s instead of adhoc.

For the move to 802.11s I would like to propose a change to the defaults, with the opportunity in the individual community profiles to override the defaults.
```
config 'defaults' '80211s'
	option 'mode' 'mesh'
	option 'encryption' 'none'
	option 'mesh_id' 'Mesh-Freifunk'
	option 'mesh_fwding' '0'
```

**Comment by pmelange** [comment]
This is implemented in PR https://github.com/freifunk/openwrt-packages/pull/3 along with an override for the profile_berlin community

**Comment by SvenRoederer** [comment]
added by fdba7969805368dd3a2ac17672710c32570a853c & 3453fe95e3b5c94a2050b04f4bc3d187b27a9c51
