### ISSUE TITLE
Update pre-set Digitalcourage DNS servers to new ip

### ISSUE THREAD

**Issue by kls0e** [freifunk/openwrt-packages#11]
While it is welcome that we suggest independent dns servers in our firmwares, the currently used pre-set ip of Digitalcourage 85.214.20.141 will expire in a couple of months. We should revise and update the default dns server ips (i.e. for Digitalcourage 46.182.19.48 respectively 2a02:2970:1002::18 as stated [here](https://digitalcourage.de/support/zensurfreier-dns-server)).

**Comment by pmelange** [comment]
PR https://github.com/freifunk/openwrt-packages/pull/16 has been submitted for the 19.x branch
PR https://github.com/openwrt/luci/pull/2776  has been submitted for the 18.x branch

<strike>TODO: changes to https://github.com/freifunk-berlin/firmware-packages</strike>

**Comment by pmelange** [comment]
This is related to https://github.com/freifunk-berlin/firmware/issues/682

**Comment by pmelange** [comment]
PR https://github.com/freifunk-berlin/firmware-packages/pull/191 has been submitted for the changes to https://github.com/freifunk-berlin/firmware-packages
