### ISSUE TITLE
theme-freifunk-generic: broken with recent OpenWrt-19.07

### ISSUE THREAD

**Issue by SvenRoederer** [freifunk/openwrt-packages#24]
Installing the "theme-freifunk-generic" results in a broken UI using recent LuCI openwrt-19.07 branch (https://github.com/openwrt/luci/commit/39a82906a1b92c8bb90e884e5a6fd41b420a9344)
Something in the page-menu seems causing the failure
![theme-ff_1907](https://user-images.githubusercontent.com/1755362/81496686-a864ba00-92b9-11ea-9149-108cddc405d5.jpeg)

This is very likely caused by the major rewrite of the LuCI-core (use more JS)

For LEDE-1701 branch the theme was working (tested with https://github.com/openwrt/luci/commit/7b230b08ebf0a1368120fe38f86593f537a80b9d):
![theme-ff_1701](https://user-images.githubusercontent.com/1755362/81496721-f974ae00-92b9-11ea-8d74-2d7a08be04d7.jpeg)

**Comment by SvenRoederer** [comment]
* the last change to the package was made nearly a year ago (June 2019; ac16b4a424b5761950a7b8d7fd7b439fe334e58d) - fix build after split from LuCI-feed
* the last general change was made nearly 1,5 years ago (Dec. 2018; 5d90e704ef33dfb9815afa9e54ba6ce60afd95a6) - done during a general fixup of all themes in the openwrt-luci feed
* the last change exclusively to the package was done nearly 2 years ago (June 2018; c32097d7d525d0c3e960e558d1c561c9c596bf96) - just a fix and backports
* the last feature change was done sometime before the LuCI-buildsystem was reworked in Dec. 2014

---

So it seems that the theme is not used any more, so let's drop it from the repo.

**Comment by andibraeu** [comment]
We have a similar issue with the bootstrap theme in luci, all menu items are missing. Within the admin backend it is working. Maybe it's an issue with the luci-freifunk package?

![image](https://user-images.githubusercontent.com/1162168/82290083-636e1100-99a6-11ea-8e0f-e8f6df2c5376.png)

**Comment by SvenRoederer** [comment]
> We have a similar issue with the bootstrap theme in luci, all menu items are missing. Within the admin backend it is working. Maybe it's an issue with the luci-freifunk package?

@andibraeu  There have been multiple issues with the freifunk luci packages (#33, #32, https://github.com/freifunk-berlin/firmware/issues/831). The issue you you mentioning sounds more like https://github.com/freifunk-berlin/firmware/issues/831

**Comment by SvenRoederer** [comment]
historical theme was dropped and replaced by a fork of OpenWrt-2020 theme in PR #30. It's still a lot different from the historical theme, but at least working a a good start for further customization.
