### ISSUE TITLE
create branch openwrt-21.02

### ISSUE THREAD

**Issue by lynxis** [freifunk/openwrt-packages#38]
Hi,

as the freifunk feeds is enabled by default in OpenWrt it would be great if you could create a branch for openwrt-21.02.
For all the other feeds I've just pushed the master to the branch openwrt-21.02

Best,
lynxis

**Comment by pmelange** [comment]
please take a look at #37

**Comment by ynezz** [comment]
FYI it's currently [blocking builds](http://buildbot.openwrt.org/openwrt-21.02/images/builders/imx6%2Fgeneric/builds/1/steps/updatefeeds/logs/stdio) of 21.02 release.

BTW I don't like the idea of having GitHub as the source for the feed and would like to change that to https://git.openwrt.org/?p=feed/freifunk.git;a=summary so please setup mirroring to this repository. [Patch](https://patchwork.ozlabs.org/project/openwrt/patch/20210216093059.25266-1-ynezz@true.cz/) posted.

**Comment by ynezz** [comment]
> please take a look at #37

Good, but this can be solved later. We would like to start working on 21.02 release, so can please someone create that openwrt-21.02 branch? Thanks!

**Comment by andibraeu** [comment]
I created the branch
