### ISSUE TITLE
How to proceed with branches?

### ISSUE THREAD

**Issue by andibraeu** [freifunk/openwrt-packages#40]
As this repo/feed is not part of future openWrt releases anymore how do we want to proceed with branches here?

At the moment we do have a branch for 19.07.

There are also things developed on the master branch.

Where should the main development take place? In master

**Comment by SvenRoederer** [comment]
The "19.07" branch was made, as our master had some issues with Openwrt-19.07.
In general I fine with not forcing us to follow openwrt branches. As long as our master builds with master and 21.02 (atm), we should just keep master. As soon as special treatment is required let's add an openwrt-21.02 branch.

**Comment by SvenRoederer** [comment]
based on #42, #45 we passed the point for a branch, which has been split at c369050aebd227c3ff2c5b9b806263e72342d726

**Comment by SvenRoederer** [comment]
also added a label "openwrt-21.02"
