### ISSUE TITLE
remove freifunk-mapupdate module

### ISSUE THREAD

**Issue by booo** [freifunk/openwrt-packages#6]
Remove the freifunk-mapupdate module. The whole software stack for this router map stack is unmaintained since a few years (> 5 years).

**Comment by SvenRoederer** [comment]
Where is this module? Just ha a look into the /modules folder but only found ```mod-freifunk``` and ```mod-freifunk-community```

**Comment by akira25** [comment]
Theres a package with that name here:
https://github.com/freifunk/openwrt-packages/tree/master/contrib/package/freifunk-mapupdate

**Comment by SvenRoederer** [comment]
@Akira25  Thanks for the pointer ...
@booo looks indeed like orphaned and unused. It as so mentions map.berlin.freifunk.net which is also gone.

**Comment by SvenRoederer** [comment]
done by 0b933b59b3bfb1b6b4ae071c76f96c972babbf92
