### ISSUE TITLE
freifunk defaults: deprecate wifi_iface and add wifi_iface_adhoc and potentially more

### ISSUE THREAD

**Issue by pmelange** [freifunk/openwrt-packages#8]
I think it would be a good idea to change the name to the more descriptive ```wifi_iface_adhoc```.  This will make it possible to generalize the code in the wizard and make it possible to add other wireless modes (p2p-go, ap, sta).

To truely be albe to generalize the wizard, another section could be added.
```
config 'defaults' 'mesh_modes'
        option adhoc 'Ad-Hoc (Veraltet)'
        option 80211s '802.11s'
        ...
        option default '80211s'
```

Additionally, as in the case with adhoc, there is a need to have special settings based on if it's 2.4Ghz or 5Ghz.  In these cases, sections like ```wifi_iface_adhoc_2``` and ```wifi_iface_adhoc_5``` could override the device agnostic settings.

**Comment by SvenRoederer** [comment]
This would break a lot of other code. Not sure if this it a clever idea, even it's syntactically a good idea.
